language: haskell

sudo: false

cache:
  directories:
  - $HOME/.cabal

before_install:
  - which agda || cabal update
  - which agda || cabal install happy alex
  - which agda || cabal install Agda
  - which agda
  - agda --version
  - make dependencies WGET="./etc/ci/wget_retry.sh"

addons:
  apt:
    packages:
    - texlive
    - wget
    - curl
    - sed
    - grep

env:
 global:
   - secure: "f8v4KvmNz0nsSwH+HwDK9lvu25GllBrvwC0rU+1DAzayJM0vcCj8/wSDAjqUcGUH2b9/fU6P2vIJ9zp9gSitgnN5tojaYdWn65OQ9H0CfZlFybpqpFBypZYvI+pFf7IPueUAnTVKdSYMn0R034Dw9CJ8APReI8fTlqMNCtgpvXI="

 matrix:
   - UPDATE_NIGHTLIES="yes"

install:
  - /bin/true

script: make OTHERFLAGS="-interaction=nonstopmode" WGET="./etc/ci/wget_retry.sh"

after_script:
 - etc/ci/update_nightlies.sh
