language: haskell

sudo: false

cache:
  directories:
  - $HOME/.cabal

before_install:
  - which agda || cabal update
  - which agda || cabal install happy alex
  - which agda || cabal install Agda
  - which agda
  - agda --version
  - make dependencies WGET="./etc/ci/wget_retry.sh"

addons:
  apt:
    packages:
    - texlive
    - wget
    - curl
    - sed
    - grep

env:
 global:
   - secure: KOZts0+HId+7PrQnSffJmSyk/e56bZwNQ1XbToA6ZMXmOKyIl7KsKTqPMDI/7yViolVTv9Ntl+icIDnLQpnX3EWr5Lc7iN/E4nzokCZj/RS3Iv5GtGcdkLIgiqZsxRET+Y7E2L7BvpLY1cwJqJ9VNM7zVYqi0LYW3PMnC9ZZlVdhpQB7N68ebDjqWlM6tRCLTckz9JwUj4r/tXsvSljAdmtUFZG5RQnEAAheIHPGARJlpyd04nM/hv4Djn4KGqQbDqf9YBLLjzyOlpmPYcyvrdT2N5VzwTfXD6WSYudjRqgU1i1cjQ+WtVuz2pB6iA8Fb2+SqICadZxejr+q9ig53vmui2G0H44MvMccFJToAHPxwIuzKUXfsXV3YiVS4kUmabX2DoVOZTaV3Gdl0yAp9PvLJoKfEMbBKGHiUEKY7iPhEnFJu5d6bQyumsD8NtuyVgYNzHWWtXowVlCtBswvLO7TCeA4JTPUHjaHmaLzDlY3quGSQt29eLg8hzeeWRxSyy+AzJymFHtjGJ6EIjLjM42uMsvi6sEe+7CknLwoDGgqjH7VDl+s3Pr5LQVPirolsJhZRJx2R1oueNWL89kiTRhSPrpqdaWem4Em+WTk1NgPQo02hl1OZUuXp3beFk1dVJuOE13ubUgq1w+nbkTGGlKWXFhnLXMk87djRh6o5OY=

 matrix:
   - UPDATE_NIGHTLIES="yes"

install:
  - /bin/true

script: make OTHERFLAGS="-interaction=nonstopmode" WGET="./etc/ci/wget_retry.sh"

after_script:
 - etc/ci/update_nightlies.sh
